dist: bionic
os: linux

language: cpp
cache: ccache

jobs:
  include:
    - os: linux
      env: BUILD_TYPE=Debug

before_install:
  - ./.travis/install-devkitpro.sh
  - source /etc/profile.d/devkit-env.sh
  - ./.travis/install-makerom.sh
  - ./.travis/install-bannertool.sh

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - sudo make -j$(nproc)
  
  - ccache -s

before_deploy:
    - mv $TRAVIS_BUILD_DIR/build/apps/3dstris-bin.3dsx $TRAVIS_BUILD_DIR/build/apps/3dstris.3dsx
    - mv $TRAVIS_BUILD_DIR/build/apps/3dstris-bin.cia $TRAVIS_BUILD_DIR/build/apps/3dstris.cia
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(grep -Po "(\d+\.)+\d+" $TRAVIS_BUILD_DIR/include/3dstris/version.hpp)-$(git log --format=%h -1)-$(date +'%Y%m%d%H%M%S')}

deploy:
  provider: releases
  edge: true
  skip_cleanup: true
  prerelease: true
  file:
    - "$TRAVIS_BUILD_DIR/build/apps/3dstris.3dsx"
    - "$TRAVIS_BUILD_DIR/build/apps/3dstris.cia"
  on:
   all_branches: true
