dist: bionic
os: linux

language: cpp
cache: ccache

jobs:
  include:
    - os: linux
      env: BUILD_TYPE=Debug

before_install:
  - ./.travis/install-devkitpro.sh
  - source /etc/profile.d/devkit-env.sh
  - ./.travis/install-makerom.sh
  - ./.travis/install-bannertool.sh

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - sudo make -j$(nproc)
  
  - ccache -s

before_deploy:
    - mv $TRAVIS_BUILD_DIR/build/apps/3dstris-bin.3dsx $TRAVIS_BUILD_DIR/build/apps/3dstris.3dsx
    - mv $TRAVIS_BUILD_DIR/build/apps/3dstris-bin.cia $TRAVIS_BUILD_DIR/build/apps/3dstris.cia
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(grep -Po "(\d+\.)+\d+" $TRAVIS_BUILD_DIR/include/3dstris/version.hpp)-$(git rev-parse --short ${TRAVIS_COMMIT})}
    - git config --local user.name "3dstris-releases"
    - git config --local user.email "nobody@nobody.com"
    - git tag $TRAVIS_TAG $TRAVIS_COMMIT

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG

  target_commitish: $TRAVIS_COMMIT

  edge: true
  skip_cleanup: true
  file:
    - "$TRAVIS_BUILD_DIR/build/apps/3dstris.3dsx"
    - "$TRAVIS_BUILD_DIR/build/apps/3dstris.cia"

branches:
  only: master
