dist: bionic
os: linux

language: cpp
cache: ccache

jobs:
  include:
    - os: linux
      env: BUILD_TYPE=Release
    - os: linux
      env: BUILD_TYPE=Debug

before_install:
  - ./.travis/install-devkitpro.sh
  - source /etc/profile.d/devkit-env.sh
  - ./.travis/install-makerom.sh
  - ./.travis/install-bannertool.sh

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - sudo make -j$(nproc)
  
  - ccache -s

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}

deploy:
  provider: releases
  edge: true
  skip_cleanup: true 
  file:
    - "build/apps/3dstris-bin"
    - "build/apps/3dstris-bin.3dsx"
    - "build/apps/3dstris-bin.cia"
  on:
    all_branches: true
